# Generated by Django 2.0.2 on 2018-09-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['sequencia'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.AreaConhecimento')),
                ('grupo_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.GrupoProcesso')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Saida')),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='grupoprocesso',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Versao'),
        ),
        migrations.AddField(
            model_name='ferramentaprocess',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
        migrations.AddField(
            model_name='entradaprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
        migrations.AlterUniqueTogether(
            name='saidaprocesso',
            unique_together={('saida', 'processo')},
        ),
        migrations.AlterUniqueTogether(
            name='ferramentaprocess',
            unique_together={('ferramenta', 'processo')},
        ),
        migrations.AlterUniqueTogether(
            name='entradaprocesso',
            unique_together={('entrada', 'processo')},
        ),
    ]
