# Generated by Django 2.0.2 on 2018-09-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoprocesso',
            options={'ordering': ['sequencia'], 'verbose_name': 'Grupo de Processo', 'verbose_name_plural': 'Grupos de Processos'},
        ),
        migrations.AlterModelOptions(
            name='versao',
            options={'ordering': ['numero'], 'verbose_name': 'Versão', 'verbose_name_plural': 'Versões'},
        ),
        migrations.RenameField(
            model_name='grupoprocesso',
            old_name='versao',
            new_name='numero',
        ),
    ]
