# Generated by Django 2.0.2 on 2018-09-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20180901_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaconhecimento',
            options={'ordering': ['codigo'], 'verbose_name': 'Área de Conhecimento', 'verbose_name_plural': 'Áreas de Conhecimento'},
        ),
        migrations.AddField(
            model_name='areaconhecimento',
            name='numero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='processos.Versao'),
            preserve_default=False,
        ),
    ]
