# Generated by Django 2.0.2 on 2018-09-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20180901_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
