# Generated by Django 2.0.2 on 2018-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20180901_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDetalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
