# Generated by Django 2.0.2 on 2018-09-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_entradadetalhe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FerramentaProcess',
            new_name='FerramentaProcesso',
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['sequencia']},
        ),
        migrations.AlterModelOptions(
            name='entradaprocesso',
            options={'ordering': ['entrada']},
        ),
    ]
